/**
 * 'Pages That you vIeW in tHIs WinDOw wont apPeAr in the broWSer history AND thEY wont LEaVE other TRACes';
 * 
 * Find the index of 'w' in the sentence (ignoring cases)
 */

 let page = 'Pages That you vIeW in tHIs WinDOw wont apPeAr in the broWSer history AND thEY wont LEaVE other TRACes';

 page = page.indexOf('w')
 page = page.toLowerCases()
 console.log(page);

const sentence1 = 'Hello Dear, how are you doing?'